---
- name: Ensure folders are available
  ansible.builtin.file:
    path: "{{ linkding_filesystem_root }}/{{ item }}"
    state: "directory"
    mode: 0700
  with_items:
    - data

- name: Ensure latest linkding image version
  community.docker.docker_image:
    name: "{{ linkding_image_name }}"
    tag: "{{ linkding_image_tag }}"
    state: present
    source: pull
    force_source: true

- name: Ensure linkding container running
  community.docker.docker_container:
    name: "{{ linkding_container_name }}"
    image: "{{ linkding_image_name }}:{{ linkding_image_tag }}"
    state: started
    restart_policy: unless-stopped
    volumes:
      - "{{ linkding_filesystem_root }}/data:/etc/linkding/data"
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    published_ports:
      - "{{ linkding_config_http_port }}:9090"
